### ISSUE TITLE
有关医疗对话

### ISSUE THREAD

**Issue by fengluochenai** [Guardianzc/DISCOpen-MedBox-DialoDiagnosis#3]
你好！请问如果想利用模型进行医疗对话应该怎么运行相关代码？

**Comment by Guardianzc** [comment]
你好，这个模型目前适用于推断症状和疾病，无法生成完整的医疗对话，另外，目前关于症状和疾病推断方面最好的模型可以参考https://github.com/lemuria-wchen/DxFormer 。关于智慧医疗的其他工作也可以参考我们课题组的 https://github.com/lemuria-wchen/imcs21 ，感谢您的提问

**Comment by fengluochenai** [comment]
非常感谢您的回答
